### ISSUE TITLE
Horizontal offset

### ISSUE THREAD

**Issue by designinterface** [SiliconLabs/platform_hardware_drivers#9]
I found that there is a horizontal offset on the display when using this library. This is caused by the ssd1306_draw function setting the higher column start address to 2; changing this value to 0 fixed the problem (i.e. command is now 0x10).

**Comment by silabs-cbarna** [comment]
Please specify the project and the affected files.
We need an image about the display. A detailed problem description is welcomed.

**Comment by silabs-cbarna** [comment]
The newer version of our drivers are available here:
https://github.com/SiliconLabs/third_party_hw_drivers_extension

Please check this repository and contact us if the feature is still buggy. In the latter case, please provide us with the project link.

**Comment by designinterface** [comment]
I haven't tried the new version but it still sets the page addressing higher column start address to 2 rather than 0 in micro_oled_ssd1306.c:

sl_status_t ssd1306_draw(const void *data)
{
  sl_status_t sc = SL_STATUS_OK;
  static const uint8_t command_table[] = {
#ifdef SSD1306_USE_PAGE_ADDRESSING_MODE

    /* Set Lower Column Start Address for Page Addressing Mode */
    0x00,

    /* Set Higher Column Start Address for Page Addressing Mode */
    0x12  <- Changing this to 0x10 fixed the horizontal offset problem for me
#else
 
![Capture](https://user-images.githubusercontent.com/16709553/212930938-772da9ae-f020-4b77-a69d-7559bea30f92.PNG)

**Comment by silabs-DanielN** [comment]
Hi @designinterface, 

Thank you for reporting this issue.
I suppose you referencing the **oled_ssd1306_i2c** driver. 
The Higher Column Start Address for Page Addressing Mode value depends on the used display. 
This driver was created for and tested with the [SparkFun Micro OLED Breakout (Qwiic)](https://www.sparkfun.com/products/14532) OLED display (64x48).
I just tested the driver with this display and I did not notice any issue with it. Please see the attached picture.

![image](https://user-images.githubusercontent.com/97036561/213450487-5e11b7f3-7a49-4735-b862-b4e7cdb7734b.png)

**With other displays (having different screen resolutions and mapping), this driver may not work properly.** 

We already implemented a new version of this driver in our Third Party Hardware Drivers extension, the new driver supports the most popular displays with both I2C and SPI interfaces. 
The extension also provides a new GLIB for these displays supporting the Adafruit GFX fonts.

![image](https://user-images.githubusercontent.com/97036561/213453434-abddb80a-0f3b-4566-9af6-4e4f6b019f39.png)

Using this extension, you can easily add drivers for displays and other external hardware to your project.

Please take a look at the extension if you need support for different displays.

[https://github.com/SiliconLabs/third_party_hw_drivers_extension](https://github.com/SiliconLabs/third_party_hw_drivers_extension)

**Comment by designinterface** [comment]
Thanks Daniel,

I thought that this might be a display specific issue. A previous poster had this issue and didn't appear to solve it so maybe this thread will help someone else.

**Comment by silabs-cbarna** [comment]
Hello designinterface,

Can we close this issue now? Or do you expect anything else?

**Comment by designinterface** [comment]
I've just tried to install the extension as above and restarted Studio but it's not available under Software Components, I tried to install it again but it says that it's already there.

**Comment by silabs-DanielN** [comment]
Please check the installation guideline here: [https://github.com/SiliconLabs/third_party_hw_drivers_extension/tree/master/doc](https://github.com/SiliconLabs/third_party_hw_drivers_extension/tree/master/doc)

Besides the written guideline, a video recording is also available showing the installation steps. (Link for the video is available in the guideline above.)

**Comment by designinterface** [comment]
I've found it now, I don't have the Evaluation tick box under Software Components -> Quality (SV 5.6.0.0) but if I untick all of the available choices I can then see the Third Party Hardware Drivers.
![Capture](https://user-images.githubusercontent.com/16709553/213491448-a1cb3a8c-f49f-4cff-bb5a-4f7af1b73251.PNG)

**Comment by silabs-DanielN** [comment]
Please update to the latest GSDK (v4.2.0), older versions have no support for the Evaluation quality level software components.

**Comment by silabs-cbarna** [comment]
Can we close the issue?
